use num_derive::{FromPrimitive, ToPrimitive};

use crate::xdr::{self, XdrDeserialize, XdrSerialize};

/// NFS Operations
#[derive(Clone, Copy, Debug, FromPrimitive, ToPrimitive)]
#[repr(u32)]
pub enum NfsOperation {
    Access = 3,
    Close = 4,
    Commit = 5,
    Create = 6,
    PurgeDelegations = 7,
    ReturnDelegation = 8,
    GetAttributes = 9,
    GetFh = 10,
    Link = 11,
    LockCreate = 12,
    LockTest = 13,
    LockRelease = 14,
    Lookup = 15,
    LookupParent = 16,
    VerifyAttributeDiff = 17,
    Open = 18,
    OpenAttrs = 19,
    OpenDowngrade = 21,
    PutFh = 22,
    PutPublicFh = 23,
    PutRootFh = 24,
    Read = 25,
    ReadDir = 26,
    ReadLink = 27,
    Remove = 28,
    Rename = 29,
    RestoreFh = 31,
    SaveFh = 32,
    SecurityInfo = 33,
    SetAttr = 34,
    Verify = 37,
    Write = 38,

    BackchannelControl = 40,
    BindConnectionToSession = 41,
    ExchangeId = 42,
    CreateSession = 43,
    DestroySession = 44,
    FreeStateId = 45,
    GetDirDelegation = 46,
    GetDeviceInfo = 47,
    GetDeviceList = 48,
    LayoutCommit = 49,
    LayoutGet = 50,
    LayoutReturn = 51,
    SecurityInfoNoName = 52,
    Sequence = 53,
    SetSSV = 54,
    TestStateIds = 55,
    WantDelegation = 56,
    DestroyClientId = 57,
    ReclaimComplete = 58,
    Illegal = 10044,
}
xdr::serde_enum!(NfsOperation);
